### ISSUE TITLE
Don't perform keyboard shortcuts when focus is in an input

### ISSUE THREAD

**Issue by kentcdodds** [storybooks/storybook-ui#60]
Particularly `⌘ ⇧ →`  and `⌘ ⇧ ←` are used in inputs to select everything from the current cursor position to the end/beginning (respectively) and I do this all the time. Here's my hack I have in `config.js` to work around the problem:

```javascript
document.body.addEventListener('keydown', event => {
  // there's a keyboard shortcut that's making it impossible to select text in inputs.
  if ((event.key === 'ArrowLeft' || event.key === 'ArrowRight') && event.shiftKey && event.metaKey && event.target.tagName === 'INPUT') {
    event.stopPropagation()
  }
})
```

Would be sweet to not have this problem at all :) And `input` is not the only place where this would apply. Textareas or anything with `contenteditable` too.

**Comment by arunoda** [comment]
Yep. This is a good one.
Could you send me a PR for this.

Here's the place you should do this: https://github.com/storybooks/storybook-ui/blob/master/src/libs/key_events.js#L20

Make sure to return false to discard the event.

**Comment by kentcdodds** [comment]
Sure, I'll give it a go. Thanks!

**Comment by kentcdodds** [comment]
A bunch of tests are broken in this repo. I'm not sure how to fix them. Could you let me know when they're fixed? Then I'll go ahead and work on this. Thanks.

**Comment by arunoda** [comment]
Check now.
Done.

**Comment by willowcheng** [comment]
Some of my stories have `<input>` components, and I can't perform any shortcuts when they are focused. By disabling the keyboard shortcut when focusing input in f9781aa, it also removes part of functionality for shortcuts.

Could we disable only shortcuts that have conflicts (`keycode('right')` and `keycode('left')`)? Even better if shortcuts assignment can avoid issues when focusing input.

**Comment by ndelangen** [comment]
Hey @willowcheng thanks for reporting! It would really help if you could open a new issue, and -if you can- provide a minimal reproduction repo?

This needs some brainstorming to solve best I think.

**Comment by willowcheng** [comment]
Hi @ndelangen, added `<input>` inside component in `./example/client/preview.js` to reproduce, check [repo](https://github.com/willowcheng/storybook-ui/tree/demo-shortcut-when-focusing-input).
