### ISSUE TITLE
Display the dimensions of the iframe on resize

### ISSUE THREAD

**Issue by ijsnow** [storybooks/storybook-ui#71]
I think it would be very useful to display the dimensions of the iframe when it gets resized similarly to the functionality of browsers when you have dev tools open.

This is a feature I wish I could have every time I use storybooks, which is just about every day on the project I'm currently working on(thanks a lot for the awesome product!).

For the reason above, I added the functionality and opened a PR for it here  https://github.com/storybooks/storybook-ui/pull/70

I'd love feedback on the addition and would love to work with you all to get it to the point that it can be merged in!

**Comment by benediktvaldez** [comment]
Closed via #70 

Thanks for the contribution @ijsnow
